apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: default
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://gluster-client:8080"
  restuser: "admin"
  secretNamespace: "default"
  secretName: "heketi-secret"