kind: Pod
apiVersion: v1
metadata:
  name: mywebserverpod
  labels:
    label: webserver
spec:
  containers:
    - name: webserver
      image: docker.io/centos/httpd
      ports:
        - name: web
          containerPort: 80
      volumeMounts:
        - name: volume-webroot
          mountPath: /var/www/html
  volumes:
    - name: volume-webroot
      persistentVolumeClaim: 
        claimName: pvc-web